on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: "buildit"
        run: |
          echo "building component b"
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: buildit
        run: |
          echo "deploying staging"
  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: component-b-prod
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: buildit
        run: |
          echo "deploying prod"
